deploy:
  env:
    MAVEN_OPTS: "-XX:MaxPermSize=256m -Xmx1g"
  script:
    - "sudo bundle"
    - "mvn clean deploy -Prultor --settings ../settings.xml"
    - "mvn clean site-deploy -Psite -Prempl --settings ../settings.xml"
merge:
  script: |
    echo "testing..."
    echo "building..."
    echo "packaging..."
  squash: true
  fast-forward: only
